### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by vburenin** [kisielk/godepgraph#22]

**Comment by kisielk** [comment]
I'm not sure what you mean by the question, supported in what way?

**Comment by vburenin** [comment]
I haven't seen much activity in this project for a while last week. Just noticed that vendor normalization was added 3 days ago. I was thinking to add bunch of features which people may need such as:

1. ignore vendor dependency
2. build a better graph that doesn't get too massive and basically useless on a large projects.
3. minify import paths(two-thee lines?), so blocks don't become too long.
4. highlight dependencies between top level packages.
5. build dependency graph only within a defined package tree
6. build dependency graph for the whole project and only one level outside of the project.
7. build project dependency graph only for external dependencies.
8. make package links clickable as one in PR that is still not merged.

Way outside of the scope of this project and needs user interaction: make dependency graph interactive to be able to collapse unnecessary at the moment dependencies.

**Comment by vburenin** [comment]
One more. Aggregate dependencies of all subpackages at certain level. There is a max level of dependency graph that is limited at 256 how deep it can go, but if I limit it to 4, I still want to see aggregated dependencies of sub packages.

These requests are not the asks to jump on and implement, it is just a list of missing features I would use. My initial question is mostly based around if this project is not active, then I just create a clone of it.

**Comment by kisielk** [comment]
I see. The answer is that I'm not actively working on adding new features to this project because it served its purpose for me the way that it is written. I continue to maintain it to keep current with new Go versions, fix bugs, etc. If some other users wish to add more features to the project, I'm happy to discuss that and accept PRs if I feel they are within the scope of how I think it should work. If I have the time, I'm also glad to help out with implementation. 

I think a lot of your suggestions are good, and a few of them seem like pretty low hanging fruit, so if you'd like to have those features included in the project I'd be glad to discuss it. I suggest making issues for each one so they can be discussed separately and then addressed individually.

Merging the outstanding PR would probably be a good start, I was hoping @nanjj would come back and address the comments but maybe he got busy with other things.

**Comment by vburenin** [comment]
Low hangings fruits might be addressed pretty quickly in the existing project.
However, after thinking about this a little more. I would prefer to see an interactive graph, it would cover ALL use cases I described as well as more others. 

Not sure how long it may take me to build one, will see if I manage to start a new project that is useful for Go community.

**Comment by kisielk** [comment]
Sure, contributions are always welcome if you decide to add anything here.
