### ISSUE TITLE
include standard library dependencies

### ISSUE THREAD

**Issue by nasht00** [kisielk/godepgraph#28]
> By default godepgraph will display packages in the standard library in the graph, though it will not delve in to their dependencies.

How do I turn this off?

The example graph does include the dependencies. How do you do that?

**Comment by paulbuis** [comment]
Have you looked at the command line options documented in the project README.md and how they are implemented in the source code? I'm not positive the README documentation is worded to exactly match what the implementation does and/or documents all the command line options. I think you want the "-d" command line option to "delve" into the library packages that live in the directories that are in GOROOT rather than GOPATH. I'm not seeing that in the README, but since main.go is only 200 lines, I've been using the source as the documentation.

**Comment by kisielk** [comment]
Yes, you can use `-d` or `-withgoroot`
